#!/bin/bash
#
# CDDL HEADER START
#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#
# CDDL HEADER END
#
# Copyright 2018 Saso Kiselkov. All rights reserved.

OUTPUT="X-TCAS"

VSI_STYLE=0
GTS820_MODE=0
SNDSET="male1"
NO_AUDIO=0

while getopts "v:s:GN" opt; do
	case "$opt" in
	v)
		VSI_STYLE="$OPTARG"
		;;
	s)
		SNDSET="$OPTARG"
		;;
	G)
		VSI_STYLE=0
		GTS820_MODE=1
		SNDSET="gts820"
		;;
	N)
		NO_AUDIO=1
		;;
	*)
		echo "Invalid option -$OPTARG" >&2
		exit 1
		;;
	esac
done

(
	cd qmake
	qmake -set GTS820_MODE "$GTS820_MODE"
	if [[ "$VSI_STYLE" = 0 ]]; then
		qmake -set VSI_DRAW_MODE 0
		qmake -set VSI_STYLE 1
	else
		qmake -set VSI_DRAW_MODE 1
		qmake -set VSI_STYLE "$VSI_STYLE"
	fi
	qmake -set XTCAS_NO_AUDIO ${NO_AUDIO}
	if [[ $(uname) = "Darwin" ]]; then
		./build-mac || exit 1
	else
		./build-win-lin || exit 1
	fi
) || exit 1

rm -rf "$OUTPUT"
mkdir -p "$OUTPUT/data/msgs"
if [[ $(uname) = "Darwin" ]]; then
	cp -r qmake/output/mac_x64 "$OUTPUT"
else
	cp -r qmake/output/{win,lin}_x64 "$OUTPUT"
fi
cp -r $SNDSET/*.wav "$OUTPUT/data/msgs"

if [[ "$VSI_STYLE" != 0 ]]; then
	cp -r fonts "$OUTPUT/data/"
fi
