#!/bin/bash

# CDDL HEADER START
#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#
# CDDL HEADER END

# Copyright 2017 Saso Kiselkov. All rights reserved.

# Invoke this script to build X-TCAS for both Windows and Linux,
# 32- & 64-bit flavors. Install the necessary mingw cross-compile utilities
# first.
# On Linux also do "apt install libopenal-dev:x86_64 libopenal-dev:i386".

# Locate libacfutils and build it if necessary
LIBACFUTILS="$(qmake -query LIBACFUTILS)"

if [ "$LIBACFUTILS" = "**Unknown**" ]; then
	echo "Please use \"qmake -set LIBACFUTILS <<path>>\" to " \
	    "point to where you have libacfutils unpacked." >&2
	exit 1
fi

# We'll try to build on N+1 CPUs we have available. The extra +1 is to allow
# for one make instance to be blocking on disk.
NCPUS=$(( $(grep 'processor[[:space:]]\+:' /proc/cpuinfo  | wc -l) + 1 ))

rm -rf release output
mkdir -p output/{win,lin}_x64

make distclean > /dev/null
qmake -set CROSS_COMPILE x86_64-w64-mingw32- && \
    qmake -spec win32-g++ && \
    make -j $NCPUS && \
    mv release/win.xpl1.dll output/win_x64/X-TCAS.xpl && \
    "$LIBACFUTILS/tools/mksyms" output/win_x64/X-TCAS.xpl > \
    output/win_x64/syms.txt
if [ $? != 0 ] ; then
	exit 1
fi

make distclean > /dev/null

qmake -spec linux-g++-64 && \
    make -j $NCPUS && \
    mv liblin.xpl.so output/lin_x64/X-TCAS.xpl
if [ $? != 0 ] ; then
	exit 1
fi

make distclean > /dev/null
